### ISSUE TITLE
[false-positive] aspx-debug-mode

### ISSUE THREAD

**Issue by aminvakil** [projectdiscovery/nuclei-templates#2105]
**Nuclei version**

```
[INF] Using Nuclei Engine 2.4.0 (latest)
```

**Nuclei template version**

```
[INF] Using Nuclei Templates 8.4.1 (latest)
```

**Template ID**

aspx-debug-mode

**Commands to Reproduce**
Run using pd-actions github repository on IIS websites.
Cannot reproduce it locally.

**Comment by ehsandeep** [comment]
@aminvakil Hey, can you add more info to this, how you validated this locally and the output of the local test?

**Comment by aminvakil** [comment]
```
$ nuclei -u http://server.torbatpak.com -t ~/nuclei-templates/misconfiguration/aspx-debug-mode.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.4.0

                projectdiscovery.io

[INF] Using Nuclei Engine 2.4.0 (latest)
[INF] Using Nuclei Templates 8.4.1 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates loaded: 1 (New: 139)
[2021-07-20 15:17:27] [aspx-debug-mode] [http] [info] http://server.torbatpak.com/Foobar-debug.aspx
```
Ah, I've just tested again (maybe I used https morning) and this is reproducing on local too.
Either way `curl` returns 404.

```
$ curl -L http://server.torbatpak.com/Foobar-debug.aspx -v
*   Trying 94.182.193.33:80...
* Connected to server.torbatpak.com (94.182.193.33) port 80 (#0)
> GET /Foobar-debug.aspx HTTP/1.1
> Host: server.torbatpak.com
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Cache-Control: private
< Content-Type: text/html; charset=utf-8
< Server: Microsoft-IIS/10.0
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< Date: Tue, 20 Jul 2021 10:49:21 GMT
< Content-Length: 3757
< 
<!DOCTYPE html>
<html>
    <head>
        <title>The resource cannot be found.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>The resource cannot be found.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. &nbsp;Please review the following URL and make sure that it is spelled correctly.
            <br><br>

            <b> Requested URL: </b>/Foobar-debug.aspx<br><br>

            <hr width=100% size=1 color=silver>

            <b>Version Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3770.0

            </font>

    </body>
</html>
<!-- 
[HttpException]: The file &#39;/Foobar-debug.aspx&#39; does not exist.
   at System.Web.UI.Util.CheckVirtualFileExists(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(VirtualPath virtualPath, Type requiredBaseType, HttpContext context, Boolean allowCrossApp)
   at System.Web.UI.PageHandlerFactory.GetHandlerHelper(HttpContext context, String requestType, VirtualPath virtualPath, String physicalPath)
   at System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
--><!-- 
* Connection #0 to host server.torbatpak.com left intact
This error page might contain sensitive information because ASP.NET is configured to show verbose error messages using &lt;customErrors mode="Off"/&gt;. Consider using &lt;customErrors mode="On"/&gt; or &lt;customErrors mode="RemoteOnly"/&gt; in production environments.-->
```

If I understood correctly this should match when return status is 200 and ... which none of them are present in this URL.

```
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'OK'
        part: body
      - type: word
        words:
          - 'Content-Length: 2'
        part: header
```
I've also tested on another aspx websites and results is the same.

**Comment by daffainfo** [comment]
@aminvakil in the request of the template, the request using DEBUG method, not GET method

**Comment by aminvakil** [comment]
Ah, sure, thanks for your quick reply!

Also for thanks for your great organization, every single one of applications are awesome!
